# Generated by Django 6.0.7 on 2026-09-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jail',
            new_name='Hotel',
        ),
    ]
