# Generated by Django 6.0.7 on 2026-08-20 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('TREASURY_SUBMITTED', 'Submitted to Treasury')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_demands', to=settings.AUTH_USER_MODEL)),
                ('jail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='master_data.jail')),
                ('shg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='master_data.shg')),
            ],
        ),
        migrations.CreateModel(
            name='DemandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Requested quantity by Jail', max_digits=10)),
                ('confirmed_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Confirmed quantity supplied by SHG', max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per Kg set by SHG', max_digits=10)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.demand')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.vegetablemaster')),
            ],
        ),
    ]
