# Generated by Django 6.0.7 on 2026-08-10 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('supply_chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demand',
            name='jail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.jail'),
        ),
        migrations.AddField(
            model_name='demand',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.shg'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.demand'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.vegetablemaster'),
        ),
        migrations.AddField(
            model_name='order',
            name='demand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.demand'),
        ),
        migrations.AddField(
            model_name='order',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.shg'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='supply_chain.order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.invoice'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='supply_chain.demand'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
