# Generated by Django 6.0.7 on 2026-08-18 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('supply_chain', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shg',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='demand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_demands', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demand',
            name='jail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='master_data.jail'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='master_data.shg'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('TREASURY_SUBMITTED', 'Submitted to Treasury')], default='DRAFT', max_length=30),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
