# Generated by Django 6.0.7 on 2026-09-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_remove_orderhistory_invoice_remove_order_demand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='jail',
            new_name='hotel',
        ),
    ]
