# Generated by Django 6.0.7 on 2026-09-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_rename_jail_hotel_rename_jail_shg_hotel'),
        ('supply_chain', '0004_rename_jail_demand_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.demand')),
                ('shg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.shg')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shg_invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/shg/')),
                ('shg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED_HU', 'Verified by Hotel User'), ('APPROVED_HA', 'Approved by Hotel Admin'), ('SUBMITTED_TREASURY', 'Submitted to Treasury'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20)),
                ('approval_file', models.FileField(blank=True, null=True, upload_to='approvals/')),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='supply_chain.order')),
            ],
        ),
    ]
