# Generated by Django 6.0.7 on 2026-08-20 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('RETURN', 'Return'), ('CANCEL', 'Cancel'), ('TREASURY_SUBMIT', 'Submitted to Treasury'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('EXPORT', 'Export'), ('OTHER', 'Other')], max_length=50)),
                ('module', models.CharField(choices=[('USERS', 'Users'), ('MASTER_DATA', 'Master Data'), ('SUPPLY_CHAIN', 'Supply Chain'), ('AUDIT', 'Audit'), ('REPORTING', 'Reporting'), ('SYSTEM', 'System')], max_length=50)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('from_status', models.CharField(blank=True, max_length=50, null=True)),
                ('to_status', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='audit_log_module_2daa1a_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_log_object__8ccc11_idx'), models.Index(fields=['user', 'created_at'], name='audit_log_user_id_3b54b4_idx'), models.Index(fields=['action', 'created_at'], name='audit_log_action_97df64_idx')],
            },
        ),
    ]
