# Generated by Django 6.0.7 on 2026-09-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('supply_chain', '0004_rename_jail_demand_hotel'),
        ('users', '0002_rename_jail_user_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jail',
            new_name='Hotel',
        ),
        migrations.RenameField(
            model_name='shg',
            old_name='jail',
            new_name='hotel',
        ),
    ]
